version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: storybench-backend
    environment:
      - PYTHONPATH=/app/src
      - ENVIRONMENT=production
    volumes:
      - ./config:/app/config:ro
      - ./output:/app/output
      - ./models:/app/models
      - ./.env:/app/.env:ro
    ports:
      - "8000:8000"
    networks:
      - storybench-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: storybench-dashboard
    environment:
      - PYTHONPATH=/app/src
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - ./streamlit_dashboard:/app/streamlit_dashboard:ro
      - ./src:/app/src:ro
      - ./.env:/app/.env:ro
    ports:
      - "8501:8501"
    networks:
      - storybench-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  storybench-network:
    driver: bridge

volumes:
  storybench-output:
  storybench-models:
